### ISSUE TITLE
大神有没有入门教程呀，编译没问题，就是编完了咋弄到R1里呀

### ISSUE THREAD

**Issue by xuexijiaoben** [billy1999/R1_DEVICE#1]
还有，说明里的代码，是已经写到app里了么，还是需要自己再写进去呀
谢谢啦

**Comment by billy1999** [comment]
> 

已经写进去了.
用adb 安装进r1

**Comment by welsend** [comment]
> 还有，说明里的代码，是已经写到app里了么，还是需要自己再写进去呀 谢谢啦

编译的app能分享下吗？谢谢

**Comment by welsend** [comment]
方便分享下apk程序吗？谢谢

**Comment by Axero-Trip** [comment]
有没有好心的大哥出个教程

**Comment by zhifeng456** [comment]
编译出错，哪位大佬帮忙搞个apk出来？谢谢。

**Comment by nzsm** [comment]
给在恩山论坛弄个图文教程把，或者录个视频也行，照葫芦画瓢，还是会的

**Comment by xuanjinok** [comment]
求教程

**Comment by 1072314512** [comment]
大佬有编辑好的吗？能发我一份吗?不会编辑也看不懂.1072314512@qq.com

**Comment by jojo729** [comment]
已经发布了一个APP, 在 release 里

**Comment by Axero-Trip** [comment]
> 已经发布了一个APP, 在 release 里

感谢老哥，晚上安装上试试

**Comment by everestlion** [comment]
感谢，安装了release的apk，但启动会卡，看了日志：无法打开录音，求问大神怎么解决

**Comment by 1072314512** [comment]
> 感谢，安装了release的apk，但启动会卡，看了日志：无法打开录音，求问大神怎么解决
我的也是不知道怎么解决

**Comment by Mr-Weik** [comment]
@1072314512  刚刷到这个文件，看文档说明，是不是没有进行这一步的原因啊？提到需要禁用 # 禁用系统 app  com.phicomm.speaker.device ，看包应该和录音之类的有关。 但只看文档不知道如何禁用

**Comment by zhifeng456** [comment]
禁用似乎需要root，不然没权限
