### ISSUE TITLE
程序包com.unisound.vui.transport.out不存在

### ISSUE THREAD

**Issue by everestlion** [billy1999/R1_DEVICE#2]
Hello, 感谢提供的源码，编译的时候出现：程序包com.unisound.vui.transport.out不存在，可以提供下这个包吗，感谢

**Comment by jojo729** [comment]
> Hello, 感谢提供的源码，编译的时候出现：程序包com.unisound.vui.transport.out不存在，可以提供下这个包吗，感谢

我这边可以直接编译成功
